<div class='container' style='margin-top:20px;margin-bottom:20px'>

<p style='margin: 0cm;text-align: center;font-size:14px;font-family: "Times New Roman", serif;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ</span></strong></p>
<p style='margin: 0cm;text-align: center;font-size:14px;font-family: "Times New Roman", serif;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">г. &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Днепр</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &laquo; 15&raquo; января 2021 г. &nbsp;</span><span style="font-size:11px;font-family: Calibri, sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></p>
<p style='margin: 5pt 0cm 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">Настоящая Политика конфиденциальности персональных данных (далее &mdash; Политика конфиденциальности) действует в отношении всей информации, которую&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Интернет-магазин &laquo;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&raquo;, &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">расположенный</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">на доменном имени <a href="http://www.loveandlust.com.ua./" style="color: rgb(149, 79, 114);"><span style="color: black;">www</span><span style="color: black;">.</span><span style="color: black;">loveandlust</span><span style="color: black;">.</span><span style="color: black;">com</span><span style="color: black;">.</span><span style="color: black;">ua</span><span style="color: black;">.</span></a>адрес магазина</span><span style="font-size:19px;font-family: Calibri, sans-serif;">, может получить о Пользователе во время использования сайта Интернет-магазина, программ и продуктов<em>&nbsp;</em>Интернет-магазина.</span></p>
<p style='margin: 5pt 0cm;text-align: center;font-size:14px;font-family: "Times New Roman", serif;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">1. ОПРЕДЕЛЕНИЕ ТЕРМИНОВ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1. &nbsp; &nbsp; В настоящей Политике конфиденциальности используются следующие термины:&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.1. &laquo;Администрация сайта Интернет-магазина (далее &mdash; Администрация сайта) &raquo; &mdash; уполномоченные сотрудники на управления сайтом, действующие от имени&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">, &nbsp;которые организуют и (или) осуществляет обработку персональных данных, а также определяет цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.2. &laquo;Персональные данные&raquo; - любая информация, относящаяся к прямо или косвенно определенному или определяемому физическому лицу (субъекту персональных данных).</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.3. &laquo;Обработка персональных данных&raquo; - любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.4. &laquo;Конфиденциальность персональных данных&raquo; - обязательное для соблюдения Оператором или иным получившим доступ к персональным данным лицом требование не допускать их распространения без согласия субъекта персональных данных или наличия иного законного основания.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.5. &laquo;Пользователь сайта Интернет-магазина (далее - Пользователь)&raquo; &mdash; лицо, имеющее доступ к Сайту, посредством сети Интернет и использующее Сайт интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.6. &laquo;Cookies&raquo; &mdash; небольшой фрагмент данных, отправленный веб-сервером и хранимый на компьютере пользователя, который веб-клиент или веб-браузер каждый раз пересылает веб-серверу в HTTP-запросе при попытке открыть страницу соответствующего сайта.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">1.1.7. &laquo;IP-адрес&raquo; &mdash; уникальный сетевой адрес узла в компьютерной сети, построенной по протоколу IP.</span></p>
<p style='margin: 5pt 0cm 5pt 22.4pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -22.4pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">2. &nbsp; &nbsp;ОБЩИЕ ПОЛОЖЕНИЯ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">2.1. &nbsp; &nbsp; Использование Пользователем сайта Интернет-магазина означает согласие с настоящей Политикой конфиденциальности и условиями обработки персональных данных Пользователя.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">2.2. &nbsp; &nbsp; В случае несогласия с условиями Политики конфиденциальности Пользователь должен прекратить использование сайта Интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">2.3. &nbsp; &nbsp; Настоящая Политика конфиденциальности применяется только к сайту Интернет-магазина &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">. Интернет-магазин не контролирует и не несет ответственность за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на сайте Интернет-магазина.&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">2.4. &nbsp; &nbsp; Администрация сайта не проверяет достоверность персональных данных, предоставляемых Пользователем сайта Интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style='margin: 0cm 0cm 0cm 22.4pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -22.4pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">3. &nbsp; &nbsp;ПРЕДМЕТ ПОЛИТИКИ КОНФИДЕНЦИАЛЬНОСТИ</span></strong></p>
<p style='margin: 0cm 0cm 0cm 22.4pt;font-size:14px;font-family: "Times New Roman", serif;text-align: left;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.1. &nbsp; &nbsp; Настоящая Политика конфиденциальности устанавливает обязательства Администрации сайта интернет-магазина по неразглашению и обеспечению режима защиты конфиденциальности персональных данных, которые Пользователь предоставляет по запросу Администрации сайта при регистрации на сайте интернет-магазина или при оформлении заказа для приобретения Товара.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2. Персональные данные, разрешённые к обработке в рамках настоящей Политики конфиденциальности, предоставляются Пользователем путём заполнения регистрационной формы на Сайте интернет-магазина &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">в разделе &nbsp;офрмелние заказа и включают в себя следующую информацию:</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2.1. фамилию, имя, отчество Пользователя;&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2.2. контактный телефон Пользователя;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2.3. адрес электронной почты (e-mail);&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2.4. адрес доставки Товара;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.2.5. место жительство Пользователя.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.3. Интернет-магазин защищает Данные, которые автоматически передаются в процессе просмотра рекламных блоков и при посещении страниц, на которых установлен статистический скрипт системы (&quot;пиксель&quot;):</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">IP адрес;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">информация из cookies;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">информация о браузере (или иной программе, которая осуществляет доступ к показу рекламы);</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">время доступа;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">адрес страницы, на которой расположен рекламный блок;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:13px;font-family: Calibri, sans-serif;">&middot; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">реферер (адрес предыдущей страницы).</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;background-color: white;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.3.1. Отключение cookies может повлечь невозможность доступа к частям сайта Интернет-магазина, требующим авторизации.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.3.2. Интернет-магазин осуществляет сбор статистики об IP-адресах своих посетителей. Данная информация используется с целью выявления и решения технических проблем, для контроля законности проводимых финансовых платежей.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">3.4. Любая иная персональная информация неоговоренная выше (история покупок, используемые браузеры и операционные системы и т.д.) подлежит надежному хранению и нераспространению, за исключением случаев, предусмотренных в п.п. 5.2. и 5.3. настоящей Политики конфиденциальности.</span></p>
<p style='margin: 5pt 0cm 5pt 22.4pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -22.4pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">4. &nbsp; &nbsp;ЦЕЛИ СБОРА ПЕРСОНАЛЬНОЙ ИНФОРМАЦИИ ПОЛЬЗОВАТЕЛЯ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1. Персональные данные Пользователя Администрация сайта интернет-магазина может использовать в целях:</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.1. Идентификации Пользователя, зарегистрированного на сайте Интернет-магазина, для оформления заказа и (или) заключения Договора купли-продажи товара дистанционным способом с &nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.2. Предоставления Пользователю доступа к персонализированным ресурсам Сайта интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.3. Установления с Пользователем обратной связи, включая направление уведомлений, запросов, касающихся использования Сайта интернет-магазина, оказания услуг, обработка запросов и заявок от Пользователя.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.4. Определения места нахождения Пользователя для обеспечения безопасности, предотвращения мошенничества.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.5. Подтверждения достоверности и полноты персональных данных, предоставленных Пользователем.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.6. Создания учетной записи для совершения покупок, если Пользователь дал согласие на создание учетной записи.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.7. Уведомления Пользователя Сайта интернет-магазина о состоянии Заказа.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.8. Обработки и получения платежей, подтверждения налога или налоговых льгот, оспаривания платежа, определения права на получение кредитной линии Пользователем.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.9. Предоставления Пользователю эффективной клиентской и технической поддержки при возникновении проблем связанных с использованием Сайта интернет-магазина.&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.10. Предоставления Пользователю с его согласия, обновлений продукции, специальных предложений, информации о ценах, новостной рассылки и иных сведений от имени Интернет-магазина или от имени партнеров Интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.11. Осуществления рекламной деятельности с согласия Пользователя.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">4.1.12. Предоставления доступа Пользователю на сайты или сервисы партнеров Интернет-магазина с целью получения продуктов, обновлений и услуг.</span></p>
<p style='margin: 5pt 0cm 5pt 17.85pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -17.85pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">5. &nbsp;СПОСОБЫ И СРОКИ ОБРАБОТКИ ПЕРСОНАЛЬНОЙ</span></strong><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span></strong><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">ИНФОРМАЦИИ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.1. Обработка персональных данных Пользователя осуществляется без ограничения срока, любым законным способом, в том числе в информационных системах персональных данных с использованием средств автоматизации или без использования таких средств.&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.2. Пользователь соглашается с тем, что Администрация сайта вправе передавать персональные данные третьим лицам, в частности, курьерским службам, организациями почтовой связи, операторам электросвязи, исключительно в целях выполнения заказа Пользователя, оформленного на Сайте интернет-магазина &laquo;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Love</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&amp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Lust</span><span style="font-size:19px;font-family: Calibri, sans-serif;">&raquo;, включая доставку Товара.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.3. Персональные данные Пользователя могут быть переданы уполномоченным органам государственной власти Украины только по основаниям и в порядке, установленным законодательством Украины.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.4. При утрате или разглашении персональных данных Администрация сайта информирует Пользователя об утрате или разглашении персональных данных.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.5. Администрация сайта принимает необходимые организационные и технические меры для защиты персональной информации Пользователя от неправомерного или случайного доступа, уничтожения, изменения, блокирования, копирования, распространения, а также от иных неправомерных действий третьих лиц.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">5.6. Администрация сайта совместно с Пользователем принимает все необходимые меры по предотвращению убытков или иных отрицательных последствий, вызванных утратой или разглашением персональных данных Пользователя.</span></p>
<p style='margin: 5pt 0cm 5pt 17.85pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -17.85pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">6. &nbsp;ОБЯЗАТЕЛЬСТВА СТОРОН</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">6.1. Пользователь обязан:</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.1.1. Предоставить информацию о персональных данных, необходимую для пользования Сайтом интернет-магазина.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.1.2. Обновить, дополнить предоставленную информацию о персональных данных в случае изменения данной информации.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">6.2. Администрация сайта обязана:</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.2.1. Использовать полученную информацию исключительно для целей, указанных в п. 4 настоящей Политики конфиденциальности.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.2.2. Обеспечить хранение конфиденциальной информации в тайне, не разглашать без предварительного письменного разрешения Пользователя, а также не осуществлять продажу, обмен, опубликование, либо разглашение иными возможными способами переданных персональных данных Пользователя, за исключением п.п. 5.2. и 5.3. настоящей Политики Конфиденциальности.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.2.3. Принимать меры предосторожности для защиты конфиденциальности персональных данных Пользователя согласно порядку, обычно используемого для защиты такого рода информации в существующем деловом обороте.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">6.2.4. Осуществить блокирование персональных данных, относящихся к соответствующему Пользователю, с момента обращения или запроса Пользователя или его законного представителя либо уполномоченного органа по защите прав субъектов персональных данных на период проверки, в случае выявления недостоверных персональных данных или неправомерных действий.</span></p>
<p style='margin: 5pt 0cm 5pt 35.7pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -17.85pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">7. &nbsp;ОТВЕТСТВЕННОСТЬ СТОРОН</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">7.1. Администрация сайта, не исполнившая свои обязательства, несёт ответственность за убытки, понесённые Пользователем в связи с неправомерным использованием персональных данных, в соответствии с законодательством Украины, за исключением случаев, предусмотренных п.п. 5.2., 5.3. и 7.2. настоящей Политики Конфиденциальности.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">7.2. В случае утраты или разглашения Конфиденциальной информации Администрация сайта не несёт ответственность, если данная конфиденциальная информация:</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">7.2.1. Стала публичным достоянием до её утраты или разглашения.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">7.2.2. Была получена от третьей стороны до момента её получения Администрацией сайта.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">7.2.3. Была разглашена с согласия Пользователя.</span></p>
<p style='margin: 5pt 0cm 5pt 35.7pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -17.85pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">8. &nbsp;РАЗРЕШЕНИЕ СПОРОВ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">8</span><span style="font-size:19px;font-family: Calibri, sans-serif;">.</span><span style="font-size:19px;font-family: Calibri, sans-serif;">1</span><span style="font-size:19px;font-family: Calibri, sans-serif;">.&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">До обращения в суд с иском по спорам, возникающим из отношений между Пользователем сайта Интернет-магазина и Администрацией сайта, обязательным является предъявление претензии (письменного предложения о добровольном урегулировании спора).&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">8.2 .Получатель претензии в течение 30 календарных дней со дня получения претензии, письменно уведомляет заявителя претензии о результатах рассмотрения претензии.&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">8.3. При не достижении соглашения спор будет передан на рассмотрение в судебный орган в соответствии с действующим законодательством Украины.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">8</span><span style="font-size:19px;font-family: Calibri, sans-serif;">.4. К настоящей Политике конфиденциальности и отношениям между Пользователем и Администрацией сайта применяется действующее законодательство&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Украины</span><span style="font-size:19px;font-family: Calibri, sans-serif;">.</span></p>
<p style='margin: 5pt 0cm 5pt 35.7pt;text-align: center;font-size:14px;font-family: "Times New Roman", serif;text-indent: -17.85pt;'><strong><span style="font-size:19px;font-family: Calibri, sans-serif;">9. &nbsp;ДОПОЛНИТЕЛЬНЫЕ УСЛОВИЯ</span></strong></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">9.1. Администрация сайта вправе вносить изменения в настоящую Политику конфиденциальности без согласия Пользователя.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">9.2. Новая Политика конфиденциальности вступает в силу с момента ее размещения на Сайте интернет-магазина, если иное не предусмотрено новой редакцией Политики конфиденциальности.</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">9.3.&nbsp;</span><span style="font-size:19px;font-family: Calibri, sans-serif;">Все предложения или вопросы по настоящей Политике конфиденциальности следует сообщать на электронную почту</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">9.4. Действующая Политика конфиденциальности размещена на странице по адресу www.loveandlust.com.ua</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">&nbsp;</span></p>
<p style='margin: 0cm;text-align: justify;font-size:14px;font-family: "Times New Roman", serif;'><span style="font-size:19px;font-family: Calibri, sans-serif;">Обновлено &laquo;15&raquo; &nbsp;января 2021 г.</span></p>
</div>