<?php include './view/header.tpl'; ?>
<div class="container">
  <header>
    <div class="row">
      <div class="col-sm-6">
        <h1 class="pull-left">1<small>/4</small></h1>
        <h3>Пользовательское соглашение<br>
          <small>Пожалуйста прочитайте текст пользовательского соглашения</small></h3>
      </div>
      <div class="col-sm-6">
        <div id="logo" class="pull-right hidden-xs"><img src="assets/image/logo.png" /></div>
      </div>
    </div>
  </header>
  <div class="row">
    <div class="col-sm-9">
      <form action="step_3.php" method="post" enctype="multipart/form-data">
        <div class="terms">
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">1. Загальні положення&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">1.1. Відповідно до ст. ст. 205, 634, 638-642, 1107-1110 Цивільного Кодексу України, в разі прийняття викладених у цьому Договорі умов, шляхом замовлення &nbsp;відповідного Програмного продукту, особа, яка провадить таке замовлення, стає Ліцензіатом (акцепт умов рівнозначний укладенню Договору) та отримує право по завершенню тестового періоду та проведення оплати на використання програмного продукту як об&apos;єкта права інтелектуальної власності.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2. Терміни</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.1. Веб-сайт або сайт &mdash; сукупність веб-сторінок, доступних у мережі Інтернет, які об&apos;єднані як за змістом, так і за навігацією під єдиним доменним ім&apos;ям.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.2. Доменне ім&apos;я інтернет-магазину &mdash; частина простору ієрархічних імен мережі Інтернет, що обслуговується групою серверів системи доменних імен (DNS-серверів) та централізовано адмініструється. Доменне ім&apos;я інтернет-магазину клієнта не адмініструється Оператором.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.3. Інтернет-магазин &mdash; веб-сайт клієнта, з якого можна вибрати та замовити потрібний товар чи послугу. При цьому розміщення споживацької інформації, замовлення товару та угода відбуваються там само на сайті інтернет-магазину.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.4. Клієнт онлайн-сервісу Wobbly.Shop (Клієнт) &mdash; фізична особа, фізична особа-підприємець або юридична особа, яка пройшла реєстрацію на Платформі&nbsp;</span><a href="https://horoshop.ua/" style="text-decoration: none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in</span></a><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">&nbsp;та отримала відповідний доступ до панелі управління з метою використання сервісів Платформи з налаштування і використання інтернет-магазину.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.5. Користувач &mdash; особа, яка переглядає інформацію в інтернет-магазині, &nbsp;замовляє, отримує товари/послуги з використанням інструментів інтернет-магазину.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.6. Онлайн-сервіс (платформа) Wobbly.Shop (Сервіс/Платформа або Платформа Wobbly.Shop) &mdash; сукупність програмних та апаратних засобів, результат комп&apos;ютерного програмування (програмний продукт) у вигляді онлайн-сервісу (платформи), який забезпечує розміщення та обробку інформації клієнта, створення особистого веб-сайту у вигляді інтернет-магазину клієнта на Платформі.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.7. Панель управління &mdash; частина програмного забезпечення Платформи, яка призначена для здійснення адміністратором інтернет-магазину основних дій з налаштування інтернет-магазину, а також дій по додаванню та налаштуванню окремих модулів, сервісів і частин інтернет-магазину, управління обліковими записами, включення спеціальних можливостей, а також багато інших дій, пов&apos;язаних з управлінням інтернет-магазину в межах технічних і функціональних можливостей Платформи.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.8. Сервіс код &mdash; набір символів, який використовується для ідентифікації клієнта.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">2.9. Тариф/Абонплата &nbsp;&ndash; ціна доступу до Сервісу/Платформи, що вказана за посиланням у мережі Інтернет&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in/#pricing</span><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3. Основні положення</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.1. За цим Ліцензійним договором у випадку оплати в строки, передбачені п. 6.1-6.4 Договору, Ліцензіар передає, а Ліцензіат (Клієнт Сервісу) приймає невиключні майнові права на строкове платне використання Програмного продукту у вигляді інтернет-магазину (надалі &ndash; Програмний продукт), яким Ліцензіат володіє та користується протягом всього строку дії цього Ліцензійного договору на визначених Ліцензіаром умовах (невиключна ліцензія) з правом передачі його третім особам (надалі &ndash; Ліцензія).</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.2. Ліцензіар передає, а Ліцензіат отримує право використання Програмного продукту за його функціональним призначенням, в тому числі отримання доступу до панелі управління інтернет-магазину клієнта, яка забезпечує створення особистого інтернет-магазину клієнта, розміщення та обробку інформації в такому інтернет-магазині та інші функції, в тому числі, але не виключно, можливості розміщення та видимості для всіх користувачів у мережі Інтернет.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.3. Надання невиключних майнових прав на користування Програмним продуктом безпосередньо пов&apos;язане з оплатою доступу до онлайн-сервісу Wobbly.Shop. Правовідносини по оплаті доступу регулюються договором про надання доступу до онлайн-сервісу Wobbly.Shop за посиланням&nbsp;</span><a href="https://horoshop.ua/oferta/" style="text-decoration: none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in/offerta</span></a><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.4. Вказані у п. 3.1 та п. 3.2 Ліцензійного договору невиключні права (невиключна ліцензія) передаються Ліцензіату на весь строк користування Програмним продуктом та розповсюджуються на весь світ.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.5. Ліцензіар гарантує, що строк, на який Ліцензіату передаються права за цим Ліцензійним договором, спливає раніше, ніж спливає строк чинності виключних майнових прав Ліцензіара на Програмний продукт.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">3.6. На підтвердження перед третіми особами обсягу та дійсності прав, визначених п. 3.1 та п. 3.2. цього Ліцензійного договору, Ліцензіар не видає &nbsp;Ліцензіату Ліцензію, як окремий документ. Акт прийому-передачі невиключних майнових прав є достатнім підтвердженням того, що Ліцензіат має невиключні права на використання Програмного продукту в своїй господарській діяльності (Ліцензію).</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4. Порядок передачі прав та встановлення Програмного продукту. Акцепт оферти</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.1. Замовлення Програмного продукту шляхом заповнення відповідних реєстраційних форм є акцептом цієї Оферти.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.2. Готовий до використання під вимоги Ліцензіата Програмний продукт передається Ліцензіату шляхом надання доступу до Сервісу за допомогою ключа доступу.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.3. Для тестування і перевірки функціональних можливостей переданого Програмного продукту Ліцензіату надається тестовий період в 14 днів.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.4. Сторони за бажанням можуть підписати Акт прийому-передачі невиключних майнових прав на Програмний продукт по завершенню тестового періоду встановленого п. 4.3. Договору. В такому випадку Акт прийому-передачі невиключних майнових прав є невід&apos;ємною частиною цього Ліцензійного договору.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.5. З моменту підписання Акту прийому-передачі невиключних майнових прав та/або проведення повної оплати Винагороди Ліцензіат отримує право користуватися Програмним продуктом.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.6. Програмне забезпечення, яке є складовою Програмного продукту, може автоматично оновлюватись з метою покращення, вдосконалення та подальшого розвитку Платформи та Програмного продукту. Ліцензіат приймаючи цю Оферту погоджується отримувати такі оновлення і дозволяєте Сервісу &nbsp;постачати їх у рамках цієї ліцензії.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">4.7. Строк дії ліцензії може бути достроково зупинений у випадку існування непогашеної заборгованості за доступ, встановлений у публічному договорі (оферті) про надання доступу до онлайн-сервісу Wobbly.Shop за посиланням&nbsp;</span><a href="https://horoshop.ua/oferta/" style="text-decoration: none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in/offerta</span></a><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5. Передача прав за цим Договором&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.1. Ліцензіат має право передати свої права і обов&apos;язки за цим договором іншій особі. Про зміну особи, якій передаються невиключні майнові права на Програмний продукт, Ліцензіат направляє відповідне повідомлення Ліцензіару на електронну адресу info@wobbly.in.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.2. Повідомлення з п. 5.1. Договору про зміну Ліцензіата має містити такі відомості про майбутнього Ліцензіата як:&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.2.1. повне найменування/прізвище, ім&apos;я та по-батькові;&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.2.2. ЄДРПОУ/РНОКПП;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.2.3. дата з якої відбувається перехід невиключні майнові права &nbsp;на Програмний продукт.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">5.3. При зміні Ліцензіата Ліцензіар протягом 5 робочих днів з моменту повідомлення від попереднього Ліцензіата, з урахуванням дати, яка зазначена в повідомленні про зміну Ліцензіата, складає новий Акт прийому-передачі невиключних майнових прав на нового Ліцензіата. З моменту підписання новим Ліцензіатом Акту прийому-передачі невиключних майнових прав, до нового Ліцензіата переходить весь комплекс прав і обов&apos;язків за цим Договором, а попередній Ліцензіат відповідно втрачає невиключні майнові права на Програмний продукт. &nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6. Винагорода</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6.1. Розмір винагороди за право використання Програмного продукту &laquo;Готовий дизайн&raquo; та/або &laquo;Розширений дизайн&raquo; залежить від обраного Програмного продукту (надалі &ndash; Винагорода) та зазначається в Акті прийому-передачі невиключних майнових прав.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6.2. Ліцензіат здійснює оплату винагороди протягом 3 (трьох) робочих днів з моменту отримання рахунку від Ліцензіара.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6.3. Виплата Винагороди за цим Договором здійснюється у гривнях, шляхом безготівкового переказу коштів на банківський рахунок Ліцензіара або за допомогою платіжних сервісів із обов&apos;язковою вказівкою сервіс-коду Ліцензіата.&nbsp;</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6.4. При оплаті через платіжні сервіси кошти, отримані на банківський рахунок Ліцензіара із призначенням платежу, що відповідає рахунку/договору/коду ЄДРПОУ/найменування Ліцензіата, визнаються для цілей цього Договору коштами, сплаченими Ліцензіатом.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">6.5. Сплачена Ліцензіатом винагорода поверненню не підлягає.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">7. Строк дії і зміна умов Оферти</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">7.1. Оферта набуває чинності з моменту розміщення у мережі Інтернет за посиланням &ndash;&nbsp;</span><a href="http://shop.wobbly.in/license" style="text-decoration: none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in/license</span></a><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">&nbsp;і діє до моменту відкликання Оферти Оператором.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">7.2. Ліцензіар залишає за собою право вносити зміни до умов Оферти та/або відкликати Оферту в будь-який момент на власний розсуд. У разі внесення Ліцензіаром змін до Оферти, такі зміни вступають у силу з моменту розміщення зміненого тексту Оферти на веб-сайті за вказаним у пункті 7.1 Договору-оферти посиланням, якщо інший строк набрання чинності змін не визначений додатково при такому розміщенні. Ліцензіар повідомляє клієнтів про зміни в умовах Оферти та/або відкликання Оферти через особистий кабінет.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt; padding: 19.5pt 0pt 15.75pt;"><span style="font-size: 18pt; font-family: Arial; font-weight: 700; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">8. Чинність ліцензії та прикінцеві положення</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">8.1. Строк дії Ліцензії на використання Програмного продукту визначається з моменту підписання Акту прийому-передачі невиключних майнових прав і діє безстроково, крім випадку, передбаченого п. 5.2 цього Договору.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">8.2. Дія Ліцензії на використання Програмного продукту припиняється, а Ліцензіат позбавляється права на використання Програмного продукту з моменту видалення Програмного продукту з серверів Ліцензіата. Підстави та порядок видалення Програмного продукту встановлено в публічному договорі (оферті) надання доступу до онлайн-сервісу Wobbly.Shop за посиланням&nbsp;</span><a href="https://horoshop.ua/oferta/" style="text-decoration: none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(30, 135, 236); font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; text-decoration: underline; text-decoration-skip: none; vertical-align: baseline; white-space: pre-wrap;">http://shop.wobbly.in/offerta</span></a><span style="font-size: 12pt; font-family: Arial; font-variant-ligatures: normal; font-variant-east-asian: normal; font-variant-position: normal; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
          <p dir="ltr" style="line-height: 1.2; background-color: rgb(255, 255, 255); margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
          <p><br></p>
          <p><br></p>
        </div>
        <div class="buttons">
          <div class="pull-right">
            <a href="step_3.php" class="btn btn-primary" >Согласиться и продолжить</a>
          </div>
        </div>
      </form>
    </div>
    <div class="col-sm-3">
      <ul class="list-group">
        <li class="list-group-item"><b>Пользовательское соглашение</b></li>
        <li class="list-group-item">Установка</li>
        <li class="list-group-item">Настройка</li>
        <li class="list-group-item">Завершение</li>
      </ul>
</div>
  </div>
</div>
<?php include './view/footer.tpl'; ?>